config/routes.rb
Testapp::Application.routes.draw do
  devise_for :users

    root :to=> 'staticpages#index'
    resources :pics

    get 'video' => 'staticpages#video'

end

app/models/pic.rb
class Pic < ActiveRecord::Base
	mount_uploader :image, ImageUploader
 	attr_accessible :hour, :emotion, :learned,
 	:image
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
	def index
		@pics = Pic.all
	end

	def new
		@pic = Pic.new
	end

	def create
		@pic = Pic.create(params[:pic])
		redirect_to pics_path
	end
end

app/controllers/staticpages_controller.rb
class StaticpagesController < ApplicationController

	def index
	end

	def video
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/staticpages_helper.rb
module StaticpagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <div class="navbar navbar-inverse">


  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <!-- <a class="brand" href="#">Firehose</a> -->
      <%= link_to 'Firehose', root_path, :class => 'brand'  %>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->
		<ul class="nav">
			<li>
        		<%= link_to 'View Pics', pics_path %>
    	</li>

      <li>
          <%= link_to 'Upload Pics', new_pic_path %>
      </li>

		
</ul>
        <ul class="nav pull-right">

      



      <% if current_user.present? %>
            <li>
              <%= link_to current_user.email, '#' %>
            </li>
            <li>
              <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %>
            </li>
          <% else %>
            <li>
              <%= link_to 'Sign In', new_user_session_path %>
            </li>

            <li>
              <%= link_to 'Sign Up',
                new_user_registration_path %>

            </li>
          <% end %>



  </ul>

      </div>
 
    </div>
  </div>
</div>
</head>
<body class="<%= params[:controller]%>">


<% if notice.present? %>
       <p class="notice"><%= notice %></p>
     <% end %>
 <% if alert.present? %>    
       <p class="alert"><%= alert %></p>
   <% end %>

<%= yield %>

</body>
</html>

app/views/pics/index.html.erb
<div class="my-wrapper text-center">
	<h1>My Pics</h1>

	<% @pics.each do |pic| %>
		<div class="span3 shadowbox centered">
			<h2>
				Hour <%= pic.hour %>
			</h2>

			<div>
				<%= image_tag pic.image %>
			</div>

			<h3 class="custom-font3">
				I feel <%= pic.emotion %>
			</h3>

			<h3  class="custom-font3">
				I learned that <%= pic.learned %>
			</h3>
		</div>
	<% end %>
</div>

app/views/pics/new.html.erb
<div class="my-wrapper text-center">
	<h1>Upload Your Pics</h1>

	<div class="span6 offset3 shadowbox">
		<%= simple_form_for @pic do |f| %>
			<%= f.input :hour, label: 'Enter the Hour' %>
			<br />

			<%= f.input :image, :as => :file %>


			<%= f.input :emotion, :label  => "What's Your Mood?" %>
			<br />
			<%= f.input :learned, :label  => "What Did You Learn?", :input_html => { :rows => 10 }, :placeholder => 'Ruby, Rails, CSS3, HTML5, Responsive Design, Databases, Models, Controllers, GitHub, Eminem is awesome - ahhhh!' %>
			<%= submit_tag "Save", :class => 'btn btn-large btn-primary' %>
		<% end %>
	</div>
</div>

app/views/staticpages/index.html.erb
<!-- span6 means takes up 6/12 columns of page, 6/12=1/2 -->

<div class="span6 offset3 stolen-surfbox">

<h1 class="custom-font3">Gemspeare</h1>

<h2 class="custom-font4">What Is Love? Tis Coding In Ruby</h2>

<%= link_to("Launch App", pics_path, :class => 'btn') %>
   		
</div>

app/views/staticpages/video.html.erb
<div class="span6 offset3 stolen-surfbox">

<h1 class="custom-font3">Gemspeare</h1>

<h2 class="custom-font4">What Is Love? Tis Coding In Ruby</h2>

<%= link_to("Launch App", pics_path, :class => 'btn') %>
   		
</div>